#
# CI Hello World
#
# Copyright (C) 2017 Assured Information Security, Inc.
# Author: Rian Quinn        <quinnr@ainfosec.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Configuration
#
language: cpp
compiler: g++
sudo: required
#
# Tokens
#
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sXcLeyDusOuy3jFgWFxokJQdwxpkSoDXLkEZVuStaFG5skfAGpUEJhDUsvRqftnodAvNYnBpIFnjGVqL86+kkucbmObGVgSRk8/owb2v5ELXo/bcZ5zOlyqroi4BTLptsbuwS31AmnHGLPqfQiRuYctXku9pPwXLrjpgnHcZsLbtl3Ci93Nyro990CuSSAR4TLaJqErBt7j9jYTLKlxAJM8VszQ2T0Hs2ptUdpIaaVlMJfVopPPxxQMR7ey3EqF5/Vpw+9pIjtbn0NGsfBalL+lTNSI25zni6/VCSgtKHiIl9t4IpRDurkFI1zajNoRKlW7f6SmuWlvnb0sxivvCiVB6NpM0qofDqZK+aqfngKR8Q9H5cFEOgNum4N7eIJvt04ToW2pgxCvlU9N1uhInwOKcvUdgXfI9hf9OL4oeWjBXMPQ6k8oMpl704WygW2cOW9DKmhOCK3wX92JQT7GVQ44IlgeapqwQ5dlhudXb2MgITGYyrBApOul8H4lzTBU7i+Q4FX/rgFG9StsnjCnmRQXUpYxKEE7OewqIv7+eznMul6Fn0Zu7LEmPZVdFyGEXsGM/2j7iuJ4UC4FWqiIDDmaFcq+/Gq9rcPDf30L9NHXWwOOTIVQ3cx3DKNsOHX8N5p1xG/H/H7/UW74gwvabalM5jyQZbVb8bZ2DqUYTQ0A="


before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - echo "$COVERITY_SCAN_TOKEN"
addons:
  apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-6
    - g++-6
  coverity_scan:
    project:
      name: "presunto7/test"
      description: "test coverity"
    notification_email: a77220@alunos.uminho.pt
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: cov
  script:
    - make
